spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/commercedb}
    username: ${DB_USER:commerce}
    password: ${DB_PASS:commerce123}
  jpa:
    properties:
      hibernate:
        default_schema: auth
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: auth
    locations: classpath:db/migration

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
